name: checks

on:
  pull_request:
    branches: [ master ]

  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.1

      - name: test venus-sector-manager
        run: make test-all

      - name: build venus-sector-manager
        run: make build-all

      - name: check venus-sector-manager
        run: make check-all
